### ISSUE TITLE
Error from windowcontrols_alignment option

### ISSUE THREAD

**Issue by AndyM48** [1-minute-to-midnight/mpv-modern-x-compact#8] opened 2023-08-21 06:15 UTC
The script option `windowcontrols_alignment=right` or `windowcontrols_alignment="right"` both produce an error:

```
[modernx] windowcontrols_alignment cannot be "right". Ignoring
[modernx] windowcontrols_alignment cannot be ""right"". Ignoring

```
The default is right, so this will only be a problem if it is set to left :)

**Comment by 1-minute-to-midnight** [comment] 2023-09-14 05:05
Can't reproduce here. Have you changed anything else in the file? Could you try updating to the latest commit and try again?

**Comment by AndyM48** [comment] 2023-09-14 07:46
This is now working fine using `windowcontrols_alignment=right`.

`windowcontrols_alignment="right"` will still throw an error, although I think this is normal.

**Comment by 1-minute-to-midnight** [comment] 2023-09-14 07:55
Then I'll be closing this issue.

**Closed as completed by 1-minute-to-midnight** 2023-09-14 07:55 UTC
